In [3]:
!pip install lxml

Collecting lxml
  Downloading lxml-6.0.0-cp313-cp313-win_amd64.whl.metadata (6.8 kB)
Downloading lxml-6.0.0-cp313-cp313-win_amd64.whl (4.0 MB)
   ---------------------------------------- 0.0/4.0 MB ? eta -:--:--
   -- ------------------------------------- 0.3/4.0 MB ? eta -:--:--
   ---------- ----------------------------- 1.0/4.0 MB 3.1 MB/s eta 0:00:01
   ------------------ --------------------- 1.8/4.0 MB 3.5 MB/s eta 0:00:01
   ---------------------------- ----------- 2.9/4.0 MB 4.0 MB/s eta 0:00:01
   ---------------------------------------  3.9/4.0 MB 4.2 MB/s eta 0:00:01
   ---------------------------------------- 4.0/4.0 MB 4.1 MB/s eta 0:00:00
Installing collected packages: lxml
Successfully installed lxml-6.0.0

[notice] A new release of pip is available: 25.1.1 -> 25.2
[notice] To update, run: python.exe -m pip install --upgrade pip

In [4]:
import numpy as np
import pandas as pd
from pandas import Series, DataFrame

In [5]:
all_dfs = pd.read_html('https://en.wikipedia.org/wiki/Apollo_program')
df = all_dfs[2].copy()[['Date', 'Designation']]

In [6]:
df['Date'] = pd.to_datetime(df['Date'].str.replace(
        '(–.+)?,', '', regex=True))

In [7]:
df = df.set_index('Date')

In [8]:
df.index

DatetimeIndex(['1966-02-26', '1966-07-05', '1966-08-25', '1967-02-21',
               '1967-11-09', '1968-01-22', '1968-04-04', '1968-10-11',
               '1968-12-21', '1969-03-03', '1969-05-18', '1969-07-16',
               '1969-11-14', '1970-04-11', '1971-01-31', '1971-07-26',
               '1972-04-16', '1972-12-07'],
              dtype='datetime64[ns]', name='Date', freq=None)

In [9]:
df.loc['1970-04-11']

Designation    Apollo 13
Name: 1970-04-11 00:00:00, dtype: object

In [13]:
df.loc['1969-07']

           Designation
Date
1969-07-16   Apollo 11

In [14]:
df.loc['1971']

           Designation
Date
1971-01-31   Apollo 14
1971-07-26   Apollo 15

In [15]:
df.loc['1968-07-01':'1972-08-31']

           Designation
Date
1968-10-11    Apollo 7
1968-12-21    Apollo 8
1969-03-03    Apollo 9
1969-05-18   Apollo 10
1969-07-16   Apollo 11
1969-11-14   Apollo 12
1970-04-11   Apollo 13
1971-01-31   Apollo 14
1971-07-26   Apollo 15
1972-04-16   Apollo 16

In [17]:
df.resample('6ME').count()

            Designation
Date
1966-02-28            1
1966-08-31            2
1967-02-28            1
1967-08-31            0
1968-02-29            2
1968-08-31            1
1969-02-28            2
1969-08-31            3
1970-02-28            1
1970-08-31            1
1971-02-28            1
1971-08-31            1
1972-02-29            0
1972-08-31            1
1973-02-28            1